// Space chapter - Black hole assets
FS.assets.invisibleworld = [
  {id : 'bottomhomewos', src : 'images/9-12/The_Wonders_of_Science/bottomhomewos.png'},
  {id : 'playwos', src : 'images/9-12/The_Wonders_of_Science/playwos.png'},
  {id : 'micwos', src : 'images/9-12/The_Wonders_of_Science/micwos.png'},
  {id : 'rwwos', src : 'images/9-12/The_Wonders_of_Science/rwwos.png'},
  {id : 'mpointswos', src : 'images/9-12/The_Wonders_of_Science/mpointswos.png'},
  {id : 'menuwos', src : 'images/9-12/The_Wonders_of_Science/menuwos.png'},
  {id : 'mapwos', src : 'images/9-12/The_Wonders_of_Science/mapwos.png'},
  {id : 'infowos', src : 'images/9-12/The_Wonders_of_Science/infowos.png'},
  {id : 'fwwos', src : 'images/9-12/The_Wonders_of_Science/fwwos.png'},
  {id : 'ctrlpnlwos', src : 'images/9-12/The_Wonders_of_Science/ctrlpnlwos.png'},
  {id : 'creditswos', src : 'images/9-12/The_Wonders_of_Science/creditswos.png'},
  {id : 'what-is-everything-made-of', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/what-is-everything-made-of.png'},
  {id : 'zooming-in', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/zooming-in.png'},
  {id : 'what-else-is-out-there', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/what-else-is-out-there.png'},
  {id : 'how-strange-can-it-get', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/how-strange-can-it-get.png'},
  {id : 'light', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/light.png'},
  {id : 'cosmicraysbtn', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/cosmicraysbtn.png'},
  {id : 'antimatter', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/antimatter.png'},
  {id : 'darkmatterdarkenergy', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/darkmatterdarkenergy.png'},
  {id : 'antimattergamepol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/antimattergamepol.png'},
  {id : 'antimattertfpol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/antimattertfpol.png'},
  {id : 'piequizpol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/piequizpol.png'},
  {id : 'cosmicrayspol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/cosmicrayspol.png'},
  {id : 'cosmicrays', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/cosmicrays.jpg'},
  {id : 'superkamiokandepol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/superkamiokandepol.png'},
  {id : 'superkamiokande', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/superkamiokande.jpg'},
  {id : 'clusterpol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/clusterpol.png'},
  {id : 'cluster', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/cluster.jpg'},
  {id : 'piechartpol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/piechartpol.png'},
  {id : 'piechartjpeg', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Else_Is_Out_There/piechartjpeg.jpg'},
  {id : 'weirdbuttruepol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/How_Strange_Can_It_Get/weirdbuttruepol.png'},
  {id : 'howstrangetfpol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/How_Strange_Can_It_Get/howstrangetfpol.png'},
  {id : 'quantumsupercomppol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/How_Strange_Can_It_Get/quantumsupercomppol.png'},
  {id : 'powerfulmicroscopesbtn', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/powerfulmicroscopesbtn.png'},
  {id : 'evensmallerbtn', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/evensmallerbtn.png'},
  {id : 'sempol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/sempol.png'},
  {id : 'sem', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/sem.jpg'},
  {id : 'bloodpol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/bloodpol.png'},
  {id : 'blood', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/blood.jpg'},
  {id : 'biggesttosmallestpol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/biggesttosmallestpol.png'},
  {id : 'bubblecluespol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/bubblecluespol.png'},
  {id : 'playingdetectivepol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/playingdetectivepol.png'},
  {id : 'bebc', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/bebc.jpg'},
  {id : 'bebcpol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/bebcpol.png'},
  {id : 'bebcinstalledpol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/bebcinstalledpol.png'},
  {id : 'bebcinstalled', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/bebcinstalled.jpg'},
  {id : 'bluebubblespol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/bluebubblespol.png'},
  {id : 'bluebubbles', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/bluebubbles.jpg'},
  {id : 'atlas', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/atlas.jpg'},
  {id : 'atlaspol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/atlaspol.png'},
  {id : 'cms', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/cms.jpg'},
  {id : 'cmspol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/cmspol.png'},
  {id : 'tunnels', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/tunnels.jpg'},
  {id : 'tunnelspol', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/tunnelspol.png'},
  {id : 'magnifyingglass', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Is_Everything_Made_Of/magnifyingglass.png'},
  {id : 'sillyquark', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/sillyquark.png'},
  {id : 'ex', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/ex.png'},
  {id : 'iwg1backbtn', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/backbtn.png'},
  {id : 'correctplank', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/correctplank.png'},
  {id : 'wrongplank', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/wrongplank.png'},
  //{id : '', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/Zooming_In/'},
];

FS.assets.space = [
	//{id : 'stud2', src : 'images/stud2.png'},
	//{id : 'homepage', src : 'images/9-12/Home_Screen/homepage.jpg'},
	//{id : 'homebtn45', src : 'images/5-8/Ancient_Civilizations/Greece/homebtn345.png'},


	{id : 'homebtn', src : 'images/5-8/Ancient_Civilizations/Greece/homebtn.png'},
	{id : 'cpbtn', src : 'images/5-8/Ancient_Civilizations/Greece/cpbtn.png'},
	{id : 'buildbtn', src : 'images/5-8/Ancient_Civilizations/Greece/buildbtn.png'},
	{id : 'mpbtn', src : 'images/5-8/Ancient_Civilizations/Greece/mpbtn.png'},
	{id : 'menubtn', src : 'images/5-8/Ancient_Civilizations/Greece/menubtn.png'},
	{id : 'bonustalk', src : 'images/5-8/Space/Black_Holes/game/bonustalk.png'},
	
	{id : 'bottomhomebh', src : 'images/5-8/bottomhomebh.png'},
	
	{id : 'audio-back', src : 'images/audio/audio-back.png'},
	{id : 'audio-play', src : 'images/audio/audio-play.png'},
	{id : 'audio-pause', src : 'images/audio/audio-pause.png'},
	{id : 'audio-forw', src : 'images/audio/audio-forw.png'},

	{id : 'bottomhome', src : 'images/5-8/bottomhome.png'},

	//home page img
	/*{id : 'blackholesbtn', src : 'images/5-8/Space/blackholesbtn.png'},
	{id : 'missiontomarsbtn', src : 'images/5-8/Space/missiontomarsbtn.png'},
	{id : 'bigbangbtn', src : 'images/5-8/Space/bigbangbtn.png'},
	{id : 'galaxiesbtn', src : 'images/5-8/Space/galaxiesbtn.png'},
	{id : 'spacetravelbtn', src : 'images/5-8/Space/spacetravelbtn.png'},
	{id : 'caambtn', src : 'images/5-8/Space/caambtn.png'},
	{id : 'moontrekbtn', src : 'images/5-8/Space/moontrekbtn.png'},
	{id : 'closeststarbtn', src : 'images/5-8/Space/closeststarbtn.png'},
	{id:'spacebg',src:'images/5-8/Space/spacebg.png'},
	*/

	//blackhole video
	//{id : 'blackholevideo', src : 'video/blackhole_3-SD_for_Apple_Devices.m4v' },

	//blackhole sub-space-bh.html mp3
	//{id : 'RevisedIntro', src : 'audio/RevisedIntro.mp3'},
	//{id : 'mainbg', src : 'audio/mainbg.mp3'},
	//sub-space-bh-whatisbh.html audio video
	//{id : 'eatinggas', src : 'video/eatinggas.m4v'},
	//{id : 'WhatIsBlackHole', src : 'audio/WhatIsBlackHole.mp3'},
	//sub-space-bh-supernova.html
	//{id : 'supernovaeso', src : "video/supernovaeso.m4v"},
	//{id : 'SuperNova', src : 'audio/SuperNova.mp3'},
	//sub-space-bh-supergiantpage.html
	//{id : 'supergiantnar', src : 'audio/supergiantnar.mp3'},
	//sub-space-bh-supergiant.html
	//{id : 'supergiant', src : 'audio/supergiant.mp3'},
	//sub-space-bh-snexplosion.html
	//{id : 'supernovahubble', src : 'video/supernovahubble.m4v'},
	//{id : 'HowBigAreThey', src : 'audio/HowBigAreThey.mp3'},
	//sub-space-bh-quassars.html
	//{id : 'quasar-sfx1', src : 'video/quasar-sfx1.m4v'},
	//{id : 'Page20_0', src : 'audio/Page20_0.mp3'},
	//sub-space-bh-nscollide.html
	//{id : 'collidingns', src : 'video/collidingns.m4v'},
	//{id : 'Page15_0', src : 'audio/Page15_0.mp3'},
	//sub-space-bh-neutron.html
	//{id : 'NeutronStar', src : 'audio/NeutronStar.mp3'},
	//sub-space-bh-lifeabh.html	
	//{id : 'page16v1', src : 'audio/page16v1.mp3'},
	//sub-space-bh-gravity.html
	//{id : 'Gravity', src : 'audio/Gravity.mp3'},
	//sub-space-bh-galaxies.html
	//{id : 'Page18_0', src : 'audio/Page18_0.mp3'},
	//sub-space-bh-formgold.html
	//{id : 'GoldFormation', src : 'audio/GoldFormation.mp3'},
	//sub-space-bh-comefrom.html
	//{id : 'WhereBlackHolesComeFrom', src : 'audio/WhereBlackHolesComeFrom.mp3'},
	//sub-space-bh-blackhole.html
	//{id : 'FromToBlackhole', src : 'audio/FromToBlackhole.mp3'},
	//sub-space-bh-binaries.html
	//{id : 'Page21', src : 'audio/Page21.mp3'},
	//sub-space-bh-bhingalaxy.html
	//{id : 'page19bh', src : 'audio/page19bh.mp3'},
	//sub-space-bh-bhgo.html
	//{id : 'Page22_0', src : 'audio/Page22_0.mp3'},

	{id : 'whatbhbtn', src : 'images/5-8/Space/Black_Holes/whatbhbtn.png'},
	{id : 'comebtn', src : 'images/5-8/Space/Black_Holes/comebtn.png'},
	{id : 'wherebtn', src : 'images/5-8/Space/Black_Holes/wherebtn.png'},
	{id : 'lifebtn', src : 'images/5-8/Space/Black_Holes/lifebtn.png'},

	{id : 'centermwpol', src : 'images/5-8/Space/Black_Holes/Life_Around_BH/centermwpol.jpg'},
	{id : 'sagittariusapol', src : 'images/5-8/Space/Black_Holes/Life_Around_BH/sagittariusapol.jpg'},
	{id : 'cygnus-x1pol', src : 'images/5-8/Space/Black_Holes/Life_Around_BH/cygnus-x1pol.jpg'},
	{id : 'andromeda', src : 'images/5-8/Space/Black_Holes/Life_Around_BH/andromeda.jpg'},
	{id : 'andromedapol', src : 'images/5-8/Space/Black_Holes/Life_Around_BH/andromedapol.jpg'},
	{id : 'ngc3079', src : 'images/5-8/Space/Black_Holes/Life_Around_BH/ngc3079.jpg'},
	{id : 'ngc3079pol', src : 'images/5-8/Space/Black_Holes/Life_Around_BH/ngc3079pol.jpg'},
	{id : 'supermassivepol', src : 'images/5-8/Space/Black_Holes/Life_Around_BH/supermassivepol.jpg'},
	{id : 'galaxiesbhpol', src : 'images/5-8/Space/Black_Holes/Life_Around_BH/galaxiesbhpol.jpg'},
	{id : 'quasarpol', src : 'images/5-8/Space/Black_Holes/Life_Around_BH/quasarpol.jpg'},
	{id : 'quasarvidpol', src : 'images/5-8/Space/Black_Holes/Life_Around_BH/quasarvidpol.jpg'},
	{id : 'binariespol', src : 'images/5-8/Space/Black_Holes/Life_Around_BH/binariespol.jpg'},

	{id : 'blackholeimage', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/blackholeimage.jpg'},
	{id : 'blackholeimage2', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/blackholeimage2.jpg'},
	{id : 'blackholeimagepol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/blackholeimagepol.jpg'},
	{id : 'blackholeimage2pol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/blackholeimage2pol.jpg'},
	{id : 'nscollidepol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/nscollidepol.jpg'},
	{id : 'seebhpol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/seebhpol.jpg'},
	{id : 'snremains', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/snremains.jpg'},
	{id : 'goldbars', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/goldbars.jpg'},
	{id : 'quiztimepol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/quiztimepol.jpg'},
	{id : 'quiztime2pol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/quiztime2pol.jpg'},
	{id : 'quiztime3back', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/quiztime3back.jpg'},
	{id : 'quiztime2back', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/quiztime2back.jpg'},
	{id : 'bbackbtn', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/backbtn.png'},
	{id : 'bsubmitbtn', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/submitbtn.png'},
	{id : 'snremainspol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/snremainspol.jpg'},
	{id : 'goldbarspol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/goldbarspol.jpg'},
	{id : 'crabnebula', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/crabnebula.jpg'},
	{id : 'crabnebulans', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/crabnebulans.jpg'},
	{id : 'crabnebulapol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/crabnebulapol.jpg'},
	{id : 'crabnebulanspol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/crabnebulanspol.jpg'},
	{id : 'nscollide2pol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/nscollide2pol.jpg'},
	{id : 'supimpressionpol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/supimpressionpol.jpg'},
	{id : 'supexplodepol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/supexplodepol.jpg'},
	{id : 'supgoldpol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/supgoldpol.jpg'},
	{id : 'supbigpol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/supbigpol.jpg'},
	{id : 'supergiantpol', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/supergiantpol.jpg'},
	{id : 'narratebtn', src : 'images/5-8/Space/Black_Holes/Where_BH_Come/narratebtn.png'},

	{id : 'gravitypol', src : 'images/5-8/Space/Black_Holes/What_is_BH/gravitypol.jpg'},
	{id : 'eatinggaspol', src : 'images/5-8/Space/Black_Holes/What_is_BH/eatinggaspol.jpg'},
  
  //added for new toolbar and audio bar
  {id:'credits',src:'images/5-8/Space/credits.png'},
  {id:'ctrlpnl',src:'images/5-8/Space/ctrlpnl.png'},
  {id:'fw',src:'images/5-8/Space/fw.png'},
  {id:'info',src:'images/5-8/Space/info.png'},
  {id:'map',src:'images/5-8/Space/map.png'},
  {id:'menu',src:'images/5-8/Space/menu.png'},
  {id:'mic',src:'images/5-8/Space/mic.png'},
  {id:'mpoints',src:'images/5-8/Space/mpoints.png'},
  {id:'play',src:'images/5-8/Space/play.png'},
  {id:'rw',src:'images/5-8/Space/rw.png'},
  //added for new toolbar and audio bar end

	//css images
	
    

	//game-bh1
	{id : 'bhbackbtn', src : 'images/5-8/Space/Black_Holes/game/backbtn.png'},
	{id : 'resetbtn', src : 'images/5-8/Space/Black_Holes/game/resetbtn.png'},
	{id : 'submitsoln', src : 'images/5-8/Space/Black_Holes/game/submitsoln.png'},
	{id : 'lock', src : 'images/5-8/Space/Black_Holes/game/lock.png'},
	{id : 'gamesupernova', src : 'images/5-8/Space/Black_Holes/game/supernova.png'},
	{id : 'gameneutronstar', src : 'images/5-8/Space/Black_Holes/game/neutronstar.png'},
	{id : 'gameblackhole', src : 'images/5-8/Space/Black_Holes/game/blackhole.png'},
	{id : 'gamesupergiant', src : 'images/5-8/Space/Black_Holes/game/supergiant.png'},
	//game-bh2
	{id : 'gamecancelbtn', src : 'images/5-8/Space/Black_Holes/game/cancelbtn.png'},
	{id : 'rocket1', src : 'images/5-8/Space/Black_Holes/game/rocket1.png'},
	{id : 'rocket2', src : 'images/5-8/Space/Black_Holes/game/rocket2.png'},
	{id : 'rocket3', src : 'images/5-8/Space/Black_Holes/game/rocket3.png'},
	{id : 'rocket4', src : 'images/5-8/Space/Black_Holes/game/rocket4.png'},
	{id : 'rocket5', src : 'images/5-8/Space/Black_Holes/game/rocket5.png'},
	{id : 'rocket6', src : 'images/5-8/Space/Black_Holes/game/rocket6.png'},
	{id : 'nozle1', src : 'images/5-8/Space/Black_Holes/game/nozle1.png'},
	{id : 'nozle2', src : 'images/5-8/Space/Black_Holes/game/nozle2.png'},
	{id : 'nozle3', src : 'images/5-8/Space/Black_Holes/game/nozle3.png'},
	{id : 'nozle4', src : 'images/5-8/Space/Black_Holes/game/nozle4.png'},
	{id : 'nozle5', src : 'images/5-8/Space/Black_Holes/game/nozle5.png'},
	{id : 'nozle6', src : 'images/5-8/Space/Black_Holes/game/nozle6.png'},
	
	{id : 'whatami', src : 'images/5-8/Space/Black_Holes/game/whatami.png'},
	//sub-space-bh-gravity.html
	{id : 'gravityq', src : 'images/5-8/Space/Black_Holes/game/gravityq.png'}	
];

FS.assets.aGreece = [
	//sub-ancient.htm
	//{id : 'greeceAncient_Greece', src : 'video/Ancient_Greece.m4v'},

	//sub-ac-greece.html
	{id : 'greecehomebtn', src : 'images/5-8/Ancient_Civilizations/Greece/homebtn.png'},
	{id : 'greececpbtn', src : 'images/5-8/Ancient_Civilizations/Greece/cpbtn.png'},
	{id : 'greecebuildbtn', src : 'images/5-8/Ancient_Civilizations/Greece/buildbtn.png'},
	{id : 'greecempbtn', src : 'images/5-8/Ancient_Civilizations/Greece/mpbtn.png'},
	{id : 'greecemenubtn', src : 'images/5-8/Ancient_Civilizations/Greece/menubtn.png'},
	
	//sub-ac-greece.html
	{id : 'greeceoagb', src : 'images/5-8/Ancient_Civilizations/Greece/oagb.png'},
	{id : 'greecelifeagb', src : 'images/5-8/Ancient_Civilizations/Greece/lifeagb.png'},
	{id : 'greecelegacyb', src : 'images/5-8/Ancient_Civilizations/Greece/legacyb.png'},
	{id : 'greecewaagbtnb', src : 'images/5-8/Ancient_Civilizations/Greece/waagbtnb.png'},
	//audio
	//{id : 'greeceIntro', src : 'audio/Intro.mp3'},

	{id : 'greecebottomhome', src : 'images/5-8/bottomhome.png'},
	{id : 'greecebonustalk', src : 'images/5-8/Ancient_Civilizations/Greece/game/bonustalk.png'},
	//player img
	{id : 'greeceaudio-back', src : 'images/audio/audio-back.png'},
	{id : 'greeceaudio-play', src : 'images/audio/audio-play.png'},
	{id : 'greeceaudio-pause', src : 'images/audio/audio-pause.png'},
	{id : 'greeceaudio-forw', src : 'images/audio/audio-forw.png'},
	//sub-ac-greece-tribes.html
	{id : 'greecetemplespol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/templespol.jpg'},
	{id : 'greeceleonidas1pol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/leonidas1pol.jpg'},
	//audio
	//{id : 'greecePage9', src : 'audio/Page9.mp3'},
	//sub-ac-greece-temple.html
	{id : 'greeceparthenon2pol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/parthenon2pol.jpg'},
	{id : 'greeceacropolispol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/acropolispol.jpg'},
	{id : 'greeceparthenon', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/parthenon.jpg'},
	{id : 'greeceacropolis', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/acropolis.jpg'},
	//audio
	//{id : 'greecePage11', src : 'audio/Page%2011.mp3'},
	//sub-ac-greece-storytelling.html
	{id : 'greecehearagpol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/hearagpol.jpg'},
	{id : 'greecesound', src : 'images/sound.png'},
	{id : 'greeceiliadpol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/iliadpol.jpg'},
	{id : 'greeceodysseypol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/odysseypol.jpg'},
	//audio
	//{id : 'greecePage15', src : 'audio/Page15.mp3'},
	//sub-ac-greece-spartans.html
	{id : 'greeceleonidaspol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/leonidaspol.jpg'},
	{id : 'greecepeloponnesepol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/peloponnesepol.jpg'},
	{id : 'greecespartancallpol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/spartancallpol.jpg'},
	{id : 'greeceleonidas', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/leonidas.jpg'},
	{id : 'greecepeloponnese', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/peloponnese.jpg'},
	//audio
	//{id : 'greecePage12', src : 'audio/Page12.mp3'},
	//sub-ac-greece-romans.html
	{id : 'greeceromepol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/romepol.jpg'},
	{id : 'greecetaorminapol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/taorminapol.jpg'},
	{id : 'greecepaestum_3pol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/paestum_3pol.jpg'},
	{id : 'greecerome', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/rome.jpg'},
	{id : 'greecetaormina', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/taormina.jpg'},
	{id : 'greecepaestum_3', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/paestum_3.jpg'},
	//audio
	//{id : 'greecePage23', src : 'audio/Page23.mp3'},
	//sub-ac-greece-phoenician.html
	{id : 'greecesidon1pol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/sidon1pol.jpg'},
	{id : 'greececarthage2pol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/carthage2pol.jpg'},
	{id : 'greececarthage1pol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/carthage1pol.jpg'},
	{id : 'greecesidon1', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/sidon1.jpg'},
	{id : 'greececarthage2', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/carthage2.jpg'},
	{id : 'greececarthage1', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/carthage1.jpg'},
	//audio
	//{id : 'greecePage27', src : 'audio/Page27.mp3'},
	//sub-ac-greece-persians.html
	{id : 'greecepersepolispol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/persepolispol.jpg'},
	{id : 'greecepersianeducpol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/persianeducpol.jpg'},
	{id : 'greecepersopolis', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/persopolis.jpg'},
	//audio
	//{id : 'greecePage24', src : 'audio/Page24.mp3'},
	//sub-ac-greece-persian-education.html
	{id : 'greecexenophonpol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/xenophonpol.jpg'},
	{id : 'greeceTomb_of_Cyruspol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/Tomb_of_Cyruspol.jpg'},
	{id : 'greecexenophon', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/xenophon.jpg'},
	{id : 'greeceTomb_of_Cyrus', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/Tomb_of_Cyrus.jpg'},
	//audio
	//{id : 'greecePage25', src : 'audio/Page25.mp3'},

	{id : 'greeceolympicq', src : 'images/5-8/Ancient_Civilizations/Greece/game/olympicq.png'},
	{id : 'greeceolym-disc', src : 'images/5-8/Ancient_Civilizations/Greece/game/olym-disc.png'},
	{id : 'greeceolym-jave', src : 'images/5-8/Ancient_Civilizations/Greece/game/olym-jave.png'},
	{id : 'greeceolym-wrest', src : 'images/5-8/Ancient_Civilizations/Greece/game/olym-wrest.png'},
	{id : 'greeceolym-bv', src : 'images/5-8/Ancient_Civilizations/Greece/game/olym-bv.png'},
	//origin
	{id : 'greecemycenaeansbtn', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/mycenaeansbtn.png'},
	{id : 'greecehittitesbtn', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/hittitesbtn.png'},
	{id : 'greecegreektribesbtn', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/greektribesbtn.png'},
	{id : 'greeceminoansbtn', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/minoansbtn.png'},
	//audio
	//{id : 'greecePage2', src : 'audio/Page2.mp3'},
	//{id : 'greecePage14', src : 'audio/Page14.mp3'},
	//{id : 'greecePage17', src : 'audio/Page17.mp3'},
	//sub-ac-greece-mycenaeans.html
	{id : 'greeceliongatepol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/liongatepol.jpg'},
	{id : 'greecemycenaetodaypol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/mycenaetodaypol.jpg'},
	{id : 'greecegoldmaskpol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/goldmaskpol.jpg'},
	{id : 'greecegoldmask', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/goldmask.jpg'},
	{id : 'greecemycenaetoday', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/mycenaetoday.jpg'},
	{id : 'greeceliongate', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/liongate.jpg'},
	//audio
	// {id : 'greecePage6mycene', src : 'audio/Page6mycene.mp3'},
	// {id : 'greecePage5', src : 'audio/Page5.mp3'},
	//sub-ac-greece-minoansend.html
	{id : 'greecesantoriniquiztimepol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/santoriniquiztimepol.jpg'},
	{id : 'greecesantorinipol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/santorinipol.jpg'},
	{id : 'greecesantorini', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/santorini.jpg'},
	//audio
	//{id : 'greecePage8b', src : 'audio/Page8b.mp3'},
	//sub-ac-greece-minoans.html
	{id : 'greecevolcanopol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/volcanopol.jpg'},
	{id : 'greecetheseuspol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/theseuspol.jpg'},
	//audio
	//{id : 'greecePage7', src : 'audio/Page7.mp3'},
	//sub-ac-greece-lydiansmoney.html
	{id : 'greecetrade-pomeg', src : 'images/5-8/Ancient_Civilizations/Greece/game/trade-pomeg.png'},
	{id : 'greecetrade-chilli', src : 'images/5-8/Ancient_Civilizations/Greece/game/trade-chilli.png'},
	{id : 'greecetrade-grapes', src : 'images/5-8/Ancient_Civilizations/Greece/game/trade-grapes.png'},
	{id : 'greecetradeq', src : 'images/5-8/Ancient_Civilizations/Greece/game/tradeq.png'},
	//audio
	//{id : 'greecePage30', src : 'audio/Page30.mp3'},
	//{id : 'greecePage22', src : 'audio/Page22.mp3'},
	//sub-ac-greece-lydians.html
	{id : 'greecelydianspol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/lydianspol.jpg'},
	{id : 'greecedelphicitypol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/delphicitypol.jpg'},
	{id : 'greecedelphicity', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/delphicity.jpg'},
	//audio
	//{id : 'greecePage20', src : 'audio/Page20.mp3'},
	//sub-ac-greece-lifeinag.html
	//audio
	//{id : 'greecePage13', src : 'audio/Page13.mp3'},
	{id : 'greeceagorabtn', src : 'images/5-8/Ancient_Civilizations/Greece/Life_in_Ancient_Greece/agorabtn.png'},
	{id : 'greeceagschoolbtn', src : 'images/5-8/Ancient_Civilizations/Greece/Life_in_Ancient_Greece/agschoolbtn.png'},
	{id : 'greecetrojanbtn', src : 'images/5-8/Ancient_Civilizations/Greece/Life_in_Ancient_Greece/trojanbtn.png'},
	{id : 'greeceolympicbtn', src : 'images/5-8/Ancient_Civilizations/Greece/Life_in_Ancient_Greece/olympicbtn.png'},
	//sub-ac-greece-legacy.html
	{id : 'greecetheatrepol', src : 'images/5-8/Ancient_Civilizations/Greece/Legacy_Of_Ancient_Greece/theatrepol.jpg'},
	{id : 'greecearchitechturepol', src : 'images/5-8/Ancient_Civilizations/Greece/Legacy_Of_Ancient_Greece/architechturepol.jpg'},
	{id : 'greecepythapol', src : 'images/5-8/Ancient_Civilizations/Greece/Legacy_Of_Ancient_Greece/pythapol.jpg'},
	{id : 'greecetheatre', src : 'images/5-8/Ancient_Civilizations/Greece/Legacy_Of_Ancient_Greece/theatre.jpg'},
	//{id : 'greecePage29', src : 'audio/Page29.mp3'},
	//sub-ac-greece-legacy-architecture.html
	{id : 'greecearchi1pol', src : 'images/5-8/Ancient_Civilizations/Greece/Legacy_Of_Ancient_Greece/archi1pol.jpg'},
	{id : 'greecearchi2pol', src : 'images/5-8/Ancient_Civilizations/Greece/Legacy_Of_Ancient_Greece/archi2pol.jpg'},
	{id : 'greecearchi3pol', src : 'images/5-8/Ancient_Civilizations/Greece/Legacy_Of_Ancient_Greece/archi3pol.jpg'},
	{id : 'greecearchi4pol', src : 'images/5-8/Ancient_Civilizations/Greece/Legacy_Of_Ancient_Greece/archi4pol.jpg'},
	{id : 'greecearchi1', src : 'images/5-8/Ancient_Civilizations/Greece/Legacy_Of_Ancient_Greece/archi1.jpg'},
	{id : 'greecearchi2', src : 'images/5-8/Ancient_Civilizations/Greece/Legacy_Of_Ancient_Greece/archi2.jpg'},
	{id : 'greecearchi3', src : 'images/5-8/Ancient_Civilizations/Greece/Legacy_Of_Ancient_Greece/archi3.jpg'},
	{id : 'greecearchi4', src : 'images/5-8/Ancient_Civilizations/Greece/Legacy_Of_Ancient_Greece/archi4.jpg'},
	//sub-ac-greece-iliad.html
	{id : 'greecetalkbubble', src : 'images/5-8/Ancient_Civilizations/Greece/game/talkbubble.png'},
	//audio
	//{id : 'greecePage16', src : 'audio/Page16.mp3'},
	//sub-ac-greece-hittites.html
	{id : 'greecehearhittitespol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/hearhittitespol.jpg'},
	{id : 'greecehittitespol', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/hittitespol.jpg'},
	{id : 'greecehittites', src : 'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/hittites.jpg'},
	//audio
	//{id : 'greecePage3', src : 'audio/Page3.mp3'},
	//sub-ac-greece-gilgamesh.html
	{id : 'greecehearinbabpol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/hearinbabpol.jpg'},
	{id : 'greecehearinengpol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/hearinengpol.jpg'},
	//audio
	// {id : 'greecegilgameshbabylonian', src : 'audio/gilgameshbabylonian.mp3'},
	// {id : 'greecegilgameshenglish', src : 'audio/gilgameshenglish.mp3'},
	
	//sub-ac-greece-egyptians.html
	{id : 'greecesphinxpol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/sphinxpol.jpg'},
	{id : 'greecepyramidspol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/pyramidspol.jpg'},
	{id : 'greeceegypt_art_2pol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/egypt_art_2pol.jpg'},
	{id : 'greeceegypt_art_1pol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/egypt_art_1pol.jpg'},
	{id : 'greecesphinx', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/sphinx.jpg'},
	{id : 'greecepyramids', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/pyramids.jpg'},
	{id : 'greeceegypt_art_2', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/egypt_art_2.jpg'},
	{id : 'greeceegypt_art_1', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/egypt_art_1.jpg'},
	//audio
	//{id : 'greecePage26', src : 'audio/Page26.mp3'},
	//sub-ac-greece-babylonians.html
	{id : 'greecebabart1pol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/babart1pol.jpg'},
	{id : 'greecebabart2pol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/babart2pol.jpg'},
	{id : 'greecereadgilgapol', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/readgilgapol.jpg'},
	{id : 'greecebabart1', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/babart1.jpg'},
	{id : 'greecebabart2', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/babart2.jpg'},
	//audio
	//{id : 'greecePage28', src : 'audio/Page28.mp3'},
	//sub-ac-greece-aroundag.html
	{id : 'greececivscramtrigger', src : 'images/5-8/Ancient_Civilizations/Greece/game/civscramtrigger.png'},
	{id : 'greeceromansicon', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/romansicon.png'},
	{id : 'greecelydiansicon', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/lydiansicon.png'},
	{id : 'greecepersiansicon', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/persiansicon.png'},
	{id : 'greecephoeniciansicon', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/phoeniciansicon.png'},
	{id : 'greecebabyloniansicon', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/babyloniansicon.png'},
	{id : 'greeceegyptiansicon', src : 'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/egyptiansicon.png'},
	//audio
	//{id : 'greecePage18', src : 'audio/Page18.mp3'},
	//sub-ac-greece-agora.html
	{id : 'greeceagora', src : 'images/5-8/Ancient_Civilizations/Greece/Life_in_Ancient_Greece/agora.jpg'},
	{id : 'greeceagorapol', src : 'images/5-8/Ancient_Civilizations/Greece/Life_in_Ancient_Greece/agorapol.jpg'},
	//audio
	//{id : 'greecePage19', src : 'audio/Page19.mp3'},

	//game-ag1.html
	{id : 'ag1-coin-save', src : 'images/5-8/Ancient_Civilizations/Greece/game/coin-save.png'},
	{id : 'ag1-coin-back', src : 'images/5-8/Ancient_Civilizations/Greece/game/coin-back.png'},
	{id : 'ag1-coin-reset', src : 'images/5-8/Ancient_Civilizations/Greece/game/coin-reset.png'},
	{id : 'ag1-icon-ag', src : 'images/5-8/Ancient_Civilizations/Greece/game/icon-ag.png'},
	{id : 'ag1-icon-persia', src : 'images/5-8/Ancient_Civilizations/Greece/game/icon-persia.png'},
	{id : 'ag1-icon-egypt', src : 'images/5-8/Ancient_Civilizations/Greece/game/icon-egypt.png'},
	{id : 'ag1-gp1', src : 'images/5-8/Ancient_Civilizations/Greece/game/gp1.png'},
	{id : 'ag1-gp2', src : 'images/5-8/Ancient_Civilizations/Greece/game/gp2.png'},
	{id : 'ag1-gp3', src : 'images/5-8/Ancient_Civilizations/Greece/game/gp3.png'},
	{id : 'ag1-gp4', src : 'images/5-8/Ancient_Civilizations/Greece/game/gp4.png'},
	{id : 'ag1-ep1', src : 'images/5-8/Ancient_Civilizations/Greece/game/ep1.png'},
	{id : 'ag1-ep2', src : 'images/5-8/Ancient_Civilizations/Greece/game/ep2.png'},
	{id : 'ag1-ep3', src : 'images/5-8/Ancient_Civilizations/Greece/game/ep3.png'},
	{id : 'ag1-ep4', src : 'images/5-8/Ancient_Civilizations/Greece/game/ep4.png'},
	{id : 'ag1-ep5', src : 'images/5-8/Ancient_Civilizations/Greece/game/ep5.png'},
	{id : 'ag1-ep6', src : 'images/5-8/Ancient_Civilizations/Greece/game/ep6.png'},
	{id : 'ag1-pp1', src : 'images/5-8/Ancient_Civilizations/Greece/game/pp1.png'},
	{id : 'ag1-pp2', src : 'images/5-8/Ancient_Civilizations/Greece/game/pp2.png'},
	{id : 'ag1-pp3', src : 'images/5-8/Ancient_Civilizations/Greece/game/pp3.png'},
	{id : 'ag1-pp4', src : 'images/5-8/Ancient_Civilizations/Greece/game/pp4.png'},
	{id : 'ag1-pp5', src : 'images/5-8/Ancient_Civilizations/Greece/game/pp5.png'},
	{id : 'ag1-pp6', src : 'images/5-8/Ancient_Civilizations/Greece/game/pp6.png'},
	{id : 'ag1-pp7', src : 'images/5-8/Ancient_Civilizations/Greece/game/pp7.png'},
	{id : 'ag1-pp8', src : 'images/5-8/Ancient_Civilizations/Greece/game/pp8.png'},
	{id : 'ag1-pp9', src : 'images/5-8/Ancient_Civilizations/Greece/game/pp9.png'},
	{id : 'ag1-pp10', src : 'images/5-8/Ancient_Civilizations/Greece/game/pp10.png'},
	//game-ag2.html
	{id : 'ag2-board-back', src : 'images/5-8/Ancient_Civilizations/Greece/game/board-back.png'},
	{id : 'ag2-board-reset', src : 'images/5-8/Ancient_Civilizations/Greece/game/board-reset.png'},
	{id : 'ag2-board-submit', src : 'images/5-8/Ancient_Civilizations/Greece/game/board-submit.png'},
	{id : 'ag2-pot1', src : 'images/5-8/Ancient_Civilizations/Greece/game/pot1.png'},
	{id : 'ag2-pot2', src : 'images/5-8/Ancient_Civilizations/Greece/game/pot2.png'},
	{id : 'ag2-pot3', src : 'images/5-8/Ancient_Civilizations/Greece/game/pot3.png'},
	{id : 'ag2-pot4', src : 'images/5-8/Ancient_Civilizations/Greece/game/pot4.png'},
	{id : 'ag2-pot5', src : 'images/5-8/Ancient_Civilizations/Greece/game/pot5.png'},
	{id : 'ag2-wawboard', src : 'images/5-8/Ancient_Civilizations/Greece/game/wawboard.png'},
	//game-ag3.html
	{id : 'ag3-3back', src : 'images/5-8/Ancient_Civilizations/Greece/game/3back.png'},
	{id : 'ag3-3save', src : 'images/5-8/Ancient_Civilizations/Greece/game/3save.png'},
	{id : 'ag3-hop', src : 'images/5-8/Ancient_Civilizations/Greece/game/hop.png'},
	{id : 'ag3-bg', src : 'images/5-8/Ancient_Civilizations/Greece/game/bg.png'},
	{id : 'ag3-soh', src : 'images/5-8/Ancient_Civilizations/Greece/game/soh.png'},
	{id : 'ag3-bk', src : 'images/5-8/Ancient_Civilizations/Greece/game/bk.png'},
	{id : 'ag3-tm', src : 'images/5-8/Ancient_Civilizations/Greece/game/tm.png'},
	{id : 'ag3-opt', src : 'images/5-8/Ancient_Civilizations/Greece/game/opt.png'}
];


FS.assets.cssBackgroundImages = [
  {id : 'bigtosmallgamebg', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/bigtosmallgamebg.jpg'},
  {id : 'iwtape1', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwtape1.png'},
  {id : 'iwtape2', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwtape2.png'},
  {id : 'iwtape3', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwtape3.png'},
  {id : 'iwtape4', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwtape4.png'},
  {id : 'iwcheckingbar', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwcheckingbar.png'},
  {id : 'iwcorrect', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwcorrect.png'},
  {id : 'iwwrong', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwwrong.png'},
  {id : 'iwprotonchoice', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwprotonchoice.png'},
  {id : 'iwquarkchoice', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwquarkchoice.png'},
  {id : 'iwatomchoice', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwatomchoice.png'},
  {id : 'iwnucleuschoice', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwnucleuschoice.png'},
  {id : 'iwgamepaper', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwgamepaper.png'},
  {id : 'iwbackbtn', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwbackbtn.png'},
  {id : 'iwresetbtn', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwresetbtn.png'},
  {id : 'iwsubmitbtn', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwsubmitbtn.png'},
  {id : 'iwgamedialog', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/iwgamedialog.png'},
  {id : 'particlezoobg', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Is_Everything_Made_Of/particlezoobg.jpg'},
  {id : 'tq', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/tq.png'},
  {id : 'uq', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/uq.png'},
  {id : 'dq', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/dq.png'},
  {id : 'sq', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/sq.png'},
  {id : 'cq', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/cq.png'},
  {id : 'game-iw1', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/game1bg.jpg'},
  {id : 'overlayiwg1', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/game/overlay.png'},
  {id : 'quarksbg', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Is_Everything_Made_Of/quarksbg.jpg'},
  {id : 'neutronbg', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Is_Everything_Made_Of/neutronbg.jpg'},
  {id : 'buzzingelectronbg', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Is_Everything_Made_Of/buzzingelectronbg.jpg'},
  {id : 'livello', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Is_Everything_Made_Of/livello.png'},
  {id : 'magnifyhand', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Is_Everything_Made_Of/magnifyhand.png'},
  {id : 'whatiseverythingmadeofbg', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/What_Is_Everything_Made_Of/whatiseverythingmadeofbg.jpg'},
  {id : 'weirdbuttruebg', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/How_Strange_Can_It_Get/weirdbuttruebg.jpg'},
  {id : 'quantumsupercompsbg', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/How_Strange_Can_It_Get/quantumsupercompsbg.jpg'},
  {id : 'invisibleworldbg', src : 'images/9-12/The_Wonders_of_Science/Invisible_World/invisibleworldbg.jpg'},
	{id:'final_world_background',src:'images/5-8/Home_Screen/final_world_background.png'},
	//{id:'homepage',src:'images/9-12/Home_Screen/homepage.jpg'},
	{id:'bartmusic',src:'images/5-8/Home_Screen/bartmusic.png'},
	{id:'bdinosours',src:'images/5-8/Home_Screen/bdinosours.png'},
	{id:'banimals',src:'images/5-8/Home_Screen/banimals.png'},
	{id:'bhumanbody',src:'images/5-8/Home_Screen/bhumanbody.png'},
	{id:'bscience',src:'images/5-8/Home_Screen/bscience.png'},
	{id:'bpeople',src:'images/5-8/Home_Screen/bpeople.png'},
	{id:'bspace',src:'images/5-8/Home_Screen/bspace.png'},
	{id:'bculture',src:'images/5-8/Home_Screen/bculture.png'},
	{id:'bnatural',src:'images/5-8/Home_Screen/bnatural.png'},
	{id:'bmodern',src:'images/5-8/Home_Screen/bmodern.png'},
	{id:'bancient',src:'images/5-8/Home_Screen/bancient.png'},
	{id:'bfun',src:'images/5-8/Home_Screen/bfun.png'},
	{id:'ancientbg',src:'images/5-8/Ancient_Civilizations/ancientbg.jpg'},
	{id:'animalsbg',src:'images/9-12/Animals/animalsbg.jpg'},
	{id:'artandmusicbg',src:'images/9-12/Art_and_Music/artandmusicbg.jpg'},
	{id:'humanbodybg',src:'images/9-12/Human_Body/humanbodybg.jpg'},
	{id:'langcultbg',src:'images/9-12/Language_and_Culture/langcultbg.jpg'},
	{id:'peopleplacesbg',src:'images/9-12/People_and_Places/peopleplacesbg.jpg'},
	{id:'modernworldbg',src:'images/9-12/The_Modern_World/modernworldbg.jpg'},
	{id:'naturalworldbg',src:'images/9-12/The_Natural_World/naturalworldbg.jpg'},
	{id:'wondersciencebg',src:'images/9-12/The_Wonders_of_Science/wondersciencebg.jpg'},
	{id:'waagbg',src:'images/5-8/Ancient_Civilizations/Greece/World_around_Greece/waagbg.jpg'},
	{id:'agbgn',src:'images/9-12/Ancient_Civilizations/Greece/agbgn.jpg'},
	{id:'theseusbg',src:'images/5-8/Ancient_Civilizations/Greece/Origins_of_Ancient_Greece/theseusbg.jpg'},
	{id:'olympicbg',src:'images/5-8/Ancient_Civilizations/Greece/Life_in_Ancient_Greece/olympicbg.jpg'},
	{id:'iliadbg',src:'images/5-8/Ancient_Civilizations/Greece/Life_in_Ancient_Greece/iliadbg.jpg'},
	{id:'odysseybg',src:'images/5-8/Ancient_Civilizations/Greece/Life_in_Ancient_Greece/odysseybg.jpg'},
	{id:'soldiersprite12',src:'images/5-8/Ancient_Civilizations/Greece/soldiersprite12.png'},
	{id:'aglink',src:'images/5-8/Ancient_Civilizations/aglink.png'},
	{id:'egyptlink',src:'images/5-8/Ancient_Civilizations/egyptlink.png'},
	{id:'romelink',src:'images/5-8/Ancient_Civilizations/romelink.png'},
	{id:'chinalink',src:'images/5-8/Ancient_Civilizations/chinalink.png'},
	{id:'spacebg',src:'images/5-8/Space/spacebg.png'},
	{id:'spacebg2',src:'images/9-12/Space/spacebg.png'},
	{id:'bhnavbg',src:'images/5-8/Space/Black_Holes/bhnavbg.jpg'},
	{id:'bhbg',src:'images/5-8/Space/Black_Holes/bhbg.jpg'},
	{id:'supergiantbg',src:'images/5-8/Space/Black_Holes/Where_BH_Come/supergiantbg.jpg'},
	{id:'gravitybg',src:'images/5-8/Space/Black_Holes/What_is_BH/gravitybg.jpg'},
	{id:'bhcomefrombg',src:'images/5-8/Space/Black_Holes/Where_BH_Come/bhcomefrombg.jpg'},
	{id:'spacegallerybg',src:'images/spacegallery/spacegallerybg.jpg'},
	{id:'museumbg',src:'images/museum/museumbg.jpg'},
	{id:'carousel-left',src:'images/museum/carousel-left.png'},
	{id:'arousel-right',src:'images/museum/carousel-right.png'},
	{id:'taskbarbg',src:'images/taskbarbg.png'},
	{id:'cpbg',src:'images/controlpanel/cpbg.jpg'},
	{id:'cp-mzonebtn',src:'images/controlpanel/cp-mzonebtn.png'},
	{id:'cp-coachbg',src:'images/controlpanel/cp-coachbg.png'},
	{id:'cp-friendsbtn',src:'images/controlpanel/cp-friendsbtn.png'},
	{id:'cp-settingsbtn',src:'images/controlpanel/cp-settingsbtn.png'},
	{id:'cp-mpointsbtn',src:'images/controlpanel/cp-mpointsbtn.png'},
	{id:'panel-mpoints',src:'images/controlpanel/panel-mpoints.png'},
	{id:'panel-friends',src:'images/controlpanel/panel-friends.png'},
	{id:'panel-settings',src:'images/controlpanel/panel-settings.png'},
	{id:'panel-mzone',src:'images/controlpanel/panel-mzone.png'},
	{id:'sch',src:'images/9-12/Home_Screen/sch.png'},
	{id:'sct',src:'images/9-12/Home_Screen/sct.png'},
	{id:'waterfall',src:'images/9-12/Home_Screen/waterfall.png'},
	{id:'fountain',src:'images/9-12/Home_Screen/fountain.png'},
	{id:'game1bg',src:'images/5-8/Space/Black_Holes/game/game1bg.png'},
	{id:'game2bg',src:'images/5-8/Space/Black_Holes/game/game2bg.png'},
	{id:'nozlebooster',src:'images/5-8/Space/Black_Holes/game/nozlebooster.png'},
	{id:'cbl',src:'images/5-8/Space/Black_Holes/game/cbl.png'},
	{id:'cbr',src:'images/5-8/Space/Black_Holes/game/cbr.png'},
	{id:'urbracket',src:'images/5-8/Space/Black_Holes/game/urbracket.png'},
	{id:'lrbracket',src:'images/5-8/Space/Black_Holes/game/lrbracket.png'},
	{id:'arrow1',src:'images/5-8/Space/Black_Holes/game/arrow1.png'},
	{id:'arrow2',src:'images/5-8/Space/Black_Holes/game/arrow2.png'},
	{id:'bh1bq',src:'images/5-8/Space/Black_Holes/game/bh1bq.png'},
	{id:'game1bg2',src:'images/5-8/Ancient_Civilizations/Greece/game/game1bg.jpg'},
	{id:'game2bg2',src:'images/5-8/Ancient_Civilizations/Greece/game/game2bg.jpg'},
	{id:'game3bg',src:'images/5-8/Ancient_Civilizations/Greece/game/game3bg.jpg'},
	{id:'avatarcreatorbg',src:'images/avatar/avatarcreatorbg.jpg'},
	{id:'menuhousing',src:'images/5-8/Ancient_Civilizations/Greece/menuhousing.png'},
	{id:'micpanel',src:'images/audio/micpanel.png'},
  
  //for wonders of science
  {id:'wondersciencebg', src:'images/9-12/The_Wonders_of_Science/wondersciencebg.jpg'},
  
  //added for coaches
  {id:'albertsprites',src:'images/avatar/albertsprites.png'},
  {id:'apron-mary',src:'images/avatar/apron-mary.png'},
  {id:'avatar-acc',src:'images/avatar/avatar-acc.png'},
  {id:'avatar-choose',src:'images/avatar/avatar-choose.png'},
  {id:'avatar-clothes',src:'images/avatar/avatar-clothes.png'},
  {id:'avatar-eye',src:'images/avatar/avatar-eye.png'},
  {id:'avatar-fh',src:'images/avatar/avatar-fh.png'},
  {id:'avatar-gadgets',src:'images/avatar/avatar-gadgets.png'},
  {id:'avatar-head',src:'images/avatar/avatar-head.png'},
  {id:'avatar-backbtn',src:'images/avatar/avatar-backbtn.png'},
  {id:'bag-jane',src:'images/avatar/bag-jane.png'},
  {id:'bag-janeopt',src:'images/avatar/bag-janeopt.png'},
  {id:'beard',src:'images/avatar/beard.png'},
  {id:'coachalbert',src:'images/avatar/coachalbert.png'},
  {id:'coachjane',src:'images/avatar/coachjane.png'},
  {id:'coachjoe',src:'images/avatar/coachjoe.png'},
  {id:'coachmary',src:'images/avatar/coachmary.png'},
  {id:'coachmay',src:'images/avatar/coachmay.png'},
  {id:'coachrico',src:'images/avatar/coachrico.png'},
  {id:'darksg',src:'images/avatar/darksg.png'},
  {id:'gglass-jane',src:'images/avatar/gglass-jane.png'},
  {id:'glasses-albert',src:'images/avatar/glasses-albert.png'},
  {id:'glasses-joe',src:'images/avatar/glasses-joe.png'},
  {id:'glasses-mary',src:'images/avatar/glasses-mary.png'},
  {id:'glasses-may',src:'images/avatar/glasses-may.png'},
  {id:'goatee',src:'images/avatar/goatee.png'},
  {id:'hat',src:'images/avatar/hat.png'},
  {id:'hat-joe',src:'images/avatar/hat-joe.png'},
  {id:'headphone-jane',src:'images/avatar/headphone-jane.png'},
  {id:'jacket',src:'images/avatar/jacket.png'},
  {id:'jacket-chow',src:'images/avatar/jacket-show.png'},
  {id:'janesprites',src:'images/avatar/janesprites.png'},
  {id:'joesprites',src:'images/avatar/joesprites.png'},
  {id:'marysprites',src:'images/avatar/marysprites.png'},
  {id:'maysprites',src:'images/avatar/maysprites.png'},
  {id:'mg-albert',src:'images/avatar/mg-albert.png'},
  {id:'none',src:'images/avatar/none.png'},
  {id:'ricosprites',src:'images/avatar/ricosprites.png'},
  {id:'avatar-savebtn',src:'images/avatar/avatar-savebtn.png'},
  {id:'shades-jane',src:'images/avatar/shades-jane.png'},
  {id:'shades-joe',src:'images/avatar/shades-joe.png'},
  {id:'shades-mary',src:'images/avatar/shades-mary.png'},
  {id:'shades-may',src:'images/avatar/shades-may.png'},
  {id:'tab-jane',src:'images/avatar/tab-jane.png'},
  {id:'wapron-mary',src:'images/avatar/wapron-mary.png'},
  {id:'yellowsg',src:'images/avatar/yellowsg.png'},
  //added for coaches end

	//skins
	/*{id : 'sclose', src : 'skins/default/close.png'},
	{id : 's-loading', src : 'skins/default/loading.gif'},
	{id : 'snext', src : 'skins/default/next.png'},
	{id : 'spause', src : 'skins/default/pause.png'},
	{id : 'splay', src : 'skins/default/play.png'},
	{id : 'splayvideo_64', src : 'skins/default/playvideo_64.png'},
	{id : 'sprev', src : 'skins/default/prev.png'},*/
	//sprites
	{id : 'ja1', src : 'sprites/ja1.png'},
	{id : 'ja2', src : 'sprites/ja2.png'},
	{id : 'ja3', src : 'sprites/ja3.png'},
	{id : 'ja4', src : 'sprites/ja4.png'},
	{id : 'ja5', src : 'sprites/ja5.png'},
	{id : 'ja6', src : 'sprites/ja6.png'},
	{id : 'ja7', src : 'sprites/ja7.png'},
	{id : 'ja8', src : 'sprites/ja8.png'},
	{id : 'ja9', src : 'sprites/ja9.png'},
	{id : 'ja10', src : 'sprites/ja10.png'},
	{id : 'ja11', src : 'sprites/ja11.png'},
	{id : 'jae1', src : 'sprites/jae1.png'},
	{id : 'jae2', src : 'sprites/jae2.png'},
	{id : 'jae3', src : 'sprites/jae3.png'},
	{id : 'jae4', src : 'sprites/jae4.png'},
	{id : 'jae5', src : 'sprites/jae5.png'},
	{id : 'jae6', src : 'sprites/jae6.png'},
	{id : 'jae7', src : 'sprites/jae7.png'},
	{id : 'jae8', src : 'sprites/jae8.png'},
	{id : 'jae9', src : 'sprites/jae9.png'},
	{id : 'jae10', src : 'sprites/jae10.png'},
	{id : 'jae11', src : 'sprites/jae11.png'},
	{id : 'jae12', src : 'sprites/jae12.png'},
	{id : 'jae13', src : 'sprites/jae13.png'},
	{id : 'jae14', src : 'sprites/jae14.png'},
  //Avatar and coach images
	{id : 'bag-jane', src : 'images/avatar/bag-jane.png'},
	{id : 'wapron-mary', src : 'images/avatar/wapron-mary.png'},
	{id : 'apron-mary', src : 'images/avatar/apron-mary.png'},
	{id : 'jacket', src : 'images/avatar/jacket.png'},
	{id : 'tab-jane', src : 'images/avatar/tab-jane.png'},
	{id : 'beard', src : 'images/avatar/beard.png'},
	{id : 'goatee', src : 'images/avatar/goatee.png'},
	{id : 'shades-mary', src : 'images/avatar/shades-mary.png'},
	{id : 'glasses-mary', src : 'images/avatar/glasses-mary.png'},
	{id : 'shades-may', src : 'images/avatar/shades-may.png'},
	{id : 'glasses-may', src : 'images/avatar/glasses-may.png'},
	{id : 'mg-albert', src : 'images/avatar/mg-albert.png'},
	{id : 'glasses-albert', src : 'images/avatar/glasses-albert.png'},
	{id : 'gglass-jane', src : 'images/avatar/gglass-jane.png'},
	{id : 'shades-jane', src : 'images/avatar/shades-jane.png'},
	{id : 'shades-joe', src : 'images/avatar/shades-joe.png'},
	{id : 'glasses-joe', src : 'images/avatar/glasses-joe.png'},
	{id : 'yellowsg', src : 'images/avatar/yellowsg.png'},
	{id : 'darksg', src : 'images/avatar/darksg.png'},
	{id : 'headphone-jane', src : 'images/avatar/headphone-jane.png'},
	{id : 'hat-joe', src : 'images/avatar/hat-joe.png'},
	{id : 'hat', src : 'images/avatar/hat.png'},
	{id : 'marysprites', src : 'images/avatar/marysprites.png'},
	{id : 'maysprites', src : 'images/avatar/maysprites.png'},
	{id : 'albertsprites', src : 'images/avatar/albertsprites.png'},
	{id : 'janesprites', src : 'images/avatar/janesprites.png'},
	{id : 'joesprites', src : 'images/avatar/joesprites.png'},
	{id : 'ricosprites', src : 'images/avatar/ricosprites.png'}
];

//add css images to preload array
/*$.each( FS.assets.cssBackgroundImages, function() {
   FS.assets.aGreece.push(this);
   FS.assets.space.push(this);
});*/
